### ISSUE TITLE
How to use SPECTRO to calculate infrared spectrum intensities. 

### ISSUE THREAD

**Issue by xiaomai12** [ntBre/spectro#120]
Hello! I would like to inquire if the current Rust version of SPECTRO can calculate infrared spectrum intensities similar to the original Fortran version of SPECTRO. If it can, could you please provide instructions on how to operate it or any available resources? If it cannot, could you please advise on how to obtain the original Fortran version of SPECTRO? Thank you very much.

**Comment by ntBre** [comment]
Hi! Unfortunately the answer to both of your questions is no. I have not implemented intensity calculations in Rust, and the Fortran version is not open-source, so I can't share the code.

**Comment by xiaomai12** [comment]
Thank you for your prompt response! I am sorry to hear this.
