### ISSUE TITLE
Spectro trying to compile outdated version of tensor library

### ISSUE THREAD

**Issue by isolated-matrix** [ntBre/spectro#146]
I have migrated!

I'm having a minor problem compiling Spectro. While I know that you updated the libraries to remove the nightly Rust features (which was how I got pbqff working on my own computer), it seems that Spectro/cargo is trying to pull an old version of the Tensor library (c58afe5b) during the compilation.

I have searched through some of the source files, but I can't actually find any mention of the Tensor library so I cannot edit it myself. Would you be able to tell me which file calls for the libraries to be compiled so I can edit it as needed?

(Also, I am not sure how much it matters, but I noticed that the Target in the Makefile is set to Linux. I was going to change it to `aarch64-apple-darwin`, but I am not sure if that's a good idea...?)

**Comment by ntBre** [comment]
Nice!

I'd have to go back and reference the original pbqff issue to see what ended up working, but I think you can just ignore the Makefile. You also shouldn't need to update any files manually to bump tensor, you can just use 
``` 
cargo update -p tensor
```
and that should pull the latest version. Then, to compile `spectro-bin` (this is kind of a long story, but there are two packages in the `spectro` repo, one is the library called `spectro` and the binary is `spectro_bin`), I'd probably just run 

```
cargo install --path spectro_bin
```

That will install it under the name `spectro_bin` unfortunately, so you can also do

```
cargo build --release -p spectro_bin
```

and then copy/link `target/release/spectro_bin` to a different name in your `PATH` as desired. Without specifying the OS or anything like I do in the Makefile, Rust should build for the native OS/architecture by default.

This is all assuming there are no other issues with Rust versions or my use of features, so let me know if anything else goes wrong. I can reuse my release workflow from pbqff to release pre-built binaries here if needed, and I am still planning to add the combination band stuff to the default output there too.

**Comment by isolated-matrix** [comment]
It worked, thank you for your help!
